// Generated by scripts/sync-server-contract.sh from u-judge-server c7231a71a8afb721bce6ed429a14dcc51f86af00. Do not edit.
package org.mass.contract

object ServerContractFixtures {
    val messages: Map<String, String> = mapOf(
        "clock_sync_request" to """{"type":"clock_sync","clientSendTimestamp":"2026-09-26T10:00:00Z"}""",
        "clock_sync_response" to """{"type":"clock_sync_response","clientSendTimestamp":"2026-09-26T10:00:00Z","serverReceiveTimestamp":"2026-09-26T10:00:00.100Z","serverSendTimestamp":"2026-09-26T10:00:00.120Z"}""",
        "command_ack" to """{"type":"command_ack","eventId":"event-contract"}""",
        "command_rejected" to """{"type":"command_rejected","code":"invalid_reconnect_credential","eventId":"event-contract"}""",
        "command_request" to """{"type":"command","eventId":"event-contract","sequence":1,"clientTimestamp":"2026-09-26T10:00:00Z","sessionId":"session-contract","payload":{"type":"kerugi_score"}}""",
        "handshake_accepted" to """{"type":"handshake_accepted"}""",
        "handshake_rejected" to """{"type":"handshake_rejected","code":"invalid_reconnect_credential"}""",
        "handshake_request" to """{"type":"handshake","protocolVersion":"1.0","reconnectCredential":"credential-contract"}""",
        "heartbeat_ack" to """{"type":"heartbeat_ack"}""",
        "heartbeat_request" to """{"type":"heartbeat"}""",
        "metadata_response" to """{"protocolVersion":"1.0","capabilities":{"metadata":true},"peerId":"00000000-0000-4000-8000-000000000001","courtId":"court-local","serverName":"U'Judge Server","pairingPolicy":"operator-approval","serverTime":"2026-09-26T10:00:00Z"}""",
        "pairing_pending_response" to """{"requestId":"request-contract","deviceId":"android-contract","surname":"Ivanov","platform":"android","state":"pending"}""",
        "pairing_request" to """{"deviceId":"android-contract","surname":"Ivanov","platform":"android","deliveryProof":"proof-contract"}""",
        "pairing_status_accepted" to """{"type":"pairing_status","state":"accepted","deviceId":"android-contract","reconnectCredential":"credential-contract"}""",
        "pairing_status_pending" to """{"type":"pairing_status","state":"pending","deviceId":"android-contract"}""",
        "pairing_status_rejected" to """{"type":"pairing_status","state":"rejected","deviceId":"android-contract","code":"operator_rejected"}""",
        "pairing_status_request" to """{"path":"/v1/pairing-status/{requestId}","deliveryProofHeader":"X-UJudge-Pairing-Delivery-Proof"}""",
    )

    fun message(name: String): String = requireNotNull(messages[name]) { "Missing server contract fixture $name" }
}
