#!/usr/bin/env bash
# Regenerates the client contract fixtures from a u-judge-server checkout (CLI-103).
# Usage: scripts/sync-server-contract.sh <path-to-u-judge-server>
# CI checks out the server at contract/server-ref, runs this script and fails on any diff.
set -euo pipefail

server="${1:?path to a u-judge-server checkout}"
fixtures="$server/server/src/test/resources/contract/v1"
target="composeApp/src/commonTest/kotlin/org/mass/contract/ServerContractFixtures.kt"
[ -d "$fixtures" ] || { echo "No contract fixtures in $fixtures" >&2; exit 1; }

mkdir -p "$(dirname "$target")"
{
    echo "// Generated by scripts/sync-server-contract.sh from u-judge-server $(cat contract/server-ref). Do not edit."
    echo "package org.mass.contract"
    echo
    echo "object ServerContractFixtures {"
    echo "    val messages: Map<String, String> = mapOf("
    for file in $(ls "$fixtures"/*.json | sort); do
        name="$(basename "$file" .json)"
        json="$(tr -d '\n' < "$file")"
        printf '        "%s" to """%s""",\n' "$name" "$json"
    done
    echo "    )"
    echo
    echo "    fun message(name: String): String = requireNotNull(messages[name]) { \"Missing server contract fixture \$name\" }"
    echo "}"
} > "$target"
echo "Wrote $target"
